services:
  api:
    container_name: nestjs
    image: node:krypton-alpine3.23
    working_dir: /srv/api
    command: sh -c "npm install --legacy-peer-deps && npm run start:dev"
    user: 1000:1000
    volumes:
      - .:/srv/api
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: picapapas
      MYSQL_DATABASE: continua
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
